INSERT INTO TB_CM_AUTHRT (AUTHRT_CD, AUTHRT_NM, USE_YN, REG_DT, RGTR_ID, MDFCN_DT, MDFR_ID) VALUES
('ADMIN','관리자','Y', CURRENT_TIMESTAMP,'TEST',CURRENT_TIMESTAMP,'TEST');

INSERT INTO TB_CM_AUTHRT (AUTHRT_CD, AUTHRT_NM, USE_YN, REG_DT, RGTR_ID, MDFCN_DT, MDFR_ID) VALUES
('GUEST','게스트','Y', CURRENT_TIMESTAMP,'TEST',CURRENT_TIMESTAMP,'TEST');

INSERT INTO TB_CM_MENU (MENU_ID, UP_MENU_ID, MENU_NM, MENU_SEQ, MENU_URL, MENU_INDCT_YN, USE_YN, REG_DT, RGTR_ID, MDFCN_DT, MDFR_ID) VALUES
('1000',NULL,'TEST',1,'/test','Y','Y', CURRENT_TIMESTAMP,'TEST',CURRENT_TIMESTAMP,'TEST');

INSERT INTO TB_CM_MENU_AUTHRT (AUTHRT_CD, MENU_ID, USE_YN, REG_DT, RGTR_ID, MDFCN_DT, MDFR_ID) VALUES
('ADMIN', '1000', 'Y', CURRENT_TIMESTAMP,'TEST',CURRENT_TIMESTAMP,'TEST');

INSERT INTO TB_CM_USER (USER_ID, ENPSWD, USE_YN, REG_DT, RGTR_ID, MDFCN_DT, MDFR_ID) VALUES
( 'ADMIN', '+O0nKAVk8Of5RcRj5IO4ALHyxtRPbp1ACkSyybrPCvk=', 'Y', CURRENT_TIMESTAMP, 'TEST',CURRENT_TIMESTAMP,'TEST');

INSERT INTO TB_CM_USER_AUTHRT (USER_ID, AUTHRT_CD, USE_YN, REG_DT, RGTR_ID, MDFCN_DT, MDFR_ID) VALUES
('ADMIN', 'ADMIN', 'Y', CURRENT_TIMESTAMP, 'TEST',CURRENT_TIMESTAMP,'TEST');
